title: Amy Reyes # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Experienced technical writer dedicated to creating outstanding documentation and interfaces
  <br><br>
  I enjoy collaborating with UX designers and engineers, working hands-on with hardware and software 
  products to make sure the documentation is right, and learning how to improve my work and productivity
  <br><br>
  <a href="https://www.linkedin.com/in/amyreyes/">My LinkedIn Profile</a> 
  <br><br>
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
